# Generated by Django 5.1 on 2024-09-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customuser',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
